# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gifImageDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SDWebImage', '~> 4.0.0'
pod 'SDWebImage/GIF'
pod 'FLAnimatedImage', '~> 1.0'
  # Pods for gifImageDemo

end
